// <auto-generated />
using System;
using FazendaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FazendaAPI.Migrations
{
    [DbContext(typeof(FazendaAPIContext))]
    partial class FazendaAPIContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.33")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fornecedor", b =>
                {
                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeDoFornecedor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeFornecimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CNPJ");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Fornecedor");

                    b.HasData(
                        new
                        {
                            CNPJ = "12.345.678/0001-99",
                            Email = "contato@jardinsehortas.com",
                            EnderecoId = "14820768140",
                            NomeDoFornecedor = "Jardins & Hortas",
                            Status = "Ativo",
                            Telefone = "16 98765-4321",
                            TipoDeFornecimento = "Adubo"
                        },
                        new
                        {
                            CNPJ = "98.765.432/0001-00",
                            Email = "comercial@fazendaverde.com",
                            EnderecoId = "148211642500",
                            NomeDoFornecedor = "Fazenda Verde",
                            Status = "Ativo",
                            Telefone = "16 99988-7766",
                            TipoDeFornecimento = "Agrotoxico"
                        },
                        new
                        {
                            CNPJ = "11.223.344/0001-55",
                            Email = "sales@pomares.com",
                            EnderecoId = "159970101264",
                            NomeDoFornecedor = "Pomares",
                            Status = "Inativo",
                            Telefone = "16 99555-3322",
                            TipoDeFornecimento = "Geral"
                        },
                        new
                        {
                            CNPJ = "55.667.788/0001-22",
                            Email = "info@farmaciavegetal.com",
                            EnderecoId = "15997060350",
                            NomeDoFornecedor = "Farmácia Vegetal",
                            Status = "Ativo",
                            Telefone = "16 94444-7777",
                            TipoDeFornecimento = "Adubo"
                        },
                        new
                        {
                            CNPJ = "22.334.455/0001-88",
                            Email = "contato@ecogardensupply.com",
                            EnderecoId = "15997088123",
                            NomeDoFornecedor = "EcoGarden Supply",
                            Status = "Ativo",
                            Telefone = "16 93333-5555",
                            TipoDeFornecimento = "Agrotoxico"
                        });
                });

            modelBuilder.Entity("Insumo", b =>
                {
                    b.Property<string>("CodigoLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataEntrada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("FornecedorId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MililitrosAtual")
                        .HasColumnType("int");

                    b.Property<string>("NomeDoInsumo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuantidadeEntrada")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodigoLote");

                    b.HasIndex("FornecedorId");

                    b.ToTable("Insumo");

                    b.HasData(
                        new
                        {
                            CodigoLote = "A84DEF14",
                            DataEntrada = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FornecedorId = "12.345.678/0001-99",
                            Funcao = "Fertilizante",
                            MililitrosAtual = 800,
                            NomeDoInsumo = "EcoFert Plus",
                            QuantidadeEntrada = 1000,
                            Status = "Ativo"
                        },
                        new
                        {
                            CodigoLote = "FDDC48C0",
                            DataEntrada = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FornecedorId = "98.765.432/0001-00",
                            Funcao = "Agrotoxico",
                            MililitrosAtual = 450,
                            NomeDoInsumo = "BioSafe Agro",
                            QuantidadeEntrada = 500,
                            Status = "Inativo"
                        },
                        new
                        {
                            CodigoLote = "00F9C277",
                            DataEntrada = new DateTime(2024, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FornecedorId = "11.223.344/0001-55",
                            Funcao = "Adubo",
                            MililitrosAtual = 1800,
                            NomeDoInsumo = "AgroNutri Organico",
                            QuantidadeEntrada = 2000,
                            Status = "Ativo"
                        },
                        new
                        {
                            CodigoLote = "78ECB8BE",
                            DataEntrada = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2025, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FornecedorId = "55.667.788/0001-22",
                            Funcao = "Fertilizante",
                            MililitrosAtual = 1200,
                            NomeDoInsumo = "SustainaFert Natural",
                            QuantidadeEntrada = 1500,
                            Status = "Ativo"
                        },
                        new
                        {
                            CodigoLote = "517F3101",
                            DataEntrada = new DateTime(2024, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DataValidade = new DateTime(2027, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FornecedorId = "22.334.455/0001-88",
                            Funcao = "Agrotoxico",
                            MililitrosAtual = 750,
                            NomeDoInsumo = "PureSafe Agrotoxico",
                            QuantidadeEntrada = 800,
                            Status = "Ativo"
                        });
                });

            modelBuilder.Entity("Models.AplicacaoInsumo", b =>
                {
                    b.Property<int>("Registro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Registro"), 1L, 1);

                    b.Property<DateTime>("DataAplicacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("InsumoCodigoLote")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PlantacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Registro");

                    b.HasIndex("InsumoCodigoLote");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("AplicacaoInsumo");
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CNPJ");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Cliente");

                    b.HasData(
                        new
                        {
                            CNPJ = "12.345.678/0001-99",
                            Email = "contato@mercadoverde.com.br",
                            EnderecoId = "14820768140",
                            RazaoSocial = "Mercado Verde",
                            Status = "Ativo",
                            Telefone = "(11) 3456-7890"
                        },
                        new
                        {
                            CNPJ = "98.765.432/0001-00",
                            Email = "contato@hortifrutiecia.com.br",
                            EnderecoId = "148211642500",
                            RazaoSocial = "Hortifruti & Cia",
                            Status = "Ativo",
                            Telefone = "(21) 99876-5432"
                        },
                        new
                        {
                            CNPJ = "11.223.344/0001-55",
                            Email = "contato@varejaodaterra.com.br",
                            EnderecoId = "159970101264",
                            RazaoSocial = "Varejão da Terra",
                            Status = "Ativo",
                            Telefone = "(31) 3333-5555"
                        },
                        new
                        {
                            CNPJ = "22.334.455/0001-88",
                            Email = "contato@supermacadocampo.com.br",
                            EnderecoId = "15997060350",
                            RazaoSocial = "Supermercado do Campo",
                            Status = "Ativo",
                            Telefone = "(41) 4567-8901"
                        },
                        new
                        {
                            CNPJ = "24.584.762/0001-12",
                            Email = "contato@jardimhortalicas.com.br",
                            EnderecoId = "15997060350",
                            RazaoSocial = "Jardim das Hortaliças",
                            Status = "Ativo",
                            Telefone = "(41) 4567-8901"
                        });
                });

            modelBuilder.Entity("Models.Colheita", b =>
                {
                    b.Property<int>("NumeroRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NumeroRegistro"), 1L, 1);

                    b.Property<DateTime>("DataColheita")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlantacaoId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("QuantidadeColhida")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NumeroRegistro");

                    b.HasIndex("PlantacaoId");

                    b.ToTable("Colheita");
                });

            modelBuilder.Entity("Models.Endereco", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Endereco");

                    b.HasData(
                        new
                        {
                            Id = "14820768140",
                            Bairro = "COHAB",
                            CEP = "14820-768",
                            Cidade = "Américo Brasiliense",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "140",
                            Rua = "Rua Itirapina"
                        },
                        new
                        {
                            Id = "148211642500",
                            Bairro = "Jardim Santa Terezinha",
                            CEP = "14821-164",
                            Cidade = "Américo Brasiliense",
                            Complemento = "Mansão",
                            Estado = "SP",
                            Numero = "2500",
                            Rua = "Rua Alan Gustavo Brizolari"
                        },
                        new
                        {
                            Id = "159970101264",
                            Bairro = "Jardim Alvorada",
                            CEP = "15997-010",
                            Cidade = "Matão",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "1264",
                            Rua = "Rua Coronel Leão Pio de Freitas"
                        },
                        new
                        {
                            Id = "15997060350",
                            Bairro = "Vila Guarani",
                            CEP = "15997-060",
                            Cidade = "Matão",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "350",
                            Rua = "Avenida Toledo Malta"
                        },
                        new
                        {
                            Id = "15997088123",
                            Bairro = "Jardim do Bosque",
                            CEP = "15997-088",
                            Cidade = "Matão",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "123",
                            Rua = "Avenida Minas Gerais"
                        },
                        new
                        {
                            Id = "15997440120",
                            Bairro = "Jardim Novo Mundo",
                            CEP = "15997-440",
                            Cidade = "Matão",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "120",
                            Rua = "Rua Jovelino Constantino"
                        },
                        new
                        {
                            Id = "15993081140",
                            Bairro = "Residencial Olivio Benassi",
                            CEP = "15993-081",
                            Cidade = "Matão",
                            Complemento = "",
                            Estado = "SP",
                            Numero = "140",
                            Rua = "Avenida Baldan"
                        });
                });

            modelBuilder.Entity("Models.RegistroInfestacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Cauterizado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DataConclusaoTratamento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlantacaoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PragaId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantacaoId");

                    b.HasIndex("PragaId");

                    b.ToTable("RegistroInfestacao");
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Ativa")
                        .HasColumnType("bit");

                    b.Property<string>("ClienteCNPJ")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DataDaVenda")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FuncionarioCPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteCNPJ");

                    b.HasIndex("FuncionarioCPF");

                    b.ToTable("Venda");
                });

            modelBuilder.Entity("Plantacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Colheita")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CondicaoClimatica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Crescimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DataDePlantio")
                        .HasColumnType("datetime2");

                    b.Property<string>("Irrigacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalDePlantio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LuzSolar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Plantacao");
                });

            modelBuilder.Entity("Praga", b =>
                {
                    b.Property<string>("PragaId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ControleAdequado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeDaPraga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoControle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoPraga")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PragaId");

                    b.ToTable("Praga");

                    b.HasData(
                        new
                        {
                            PragaId = "001",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Pulgões",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "002",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Lagartas",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "003",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Cochonilhas",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "004",
                            ControleAdequado = "Barreiras físicas, remoção manual",
                            NomeDaPraga = "Lesmas",
                            TipoControle = "Cultural",
                            TipoPraga = "Molusco"
                        },
                        new
                        {
                            PragaId = "005",
                            ControleAdequado = "Barreiras físicas, remoção manual",
                            NomeDaPraga = "Caracóis",
                            TipoControle = "Cultural",
                            TipoPraga = "Molusco"
                        },
                        new
                        {
                            PragaId = "006",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Moscas",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "007",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Mosquitos",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "008",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Trips",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "009",
                            ControleAdequado = "Ácaros predadores",
                            NomeDaPraga = "Ácaros",
                            TipoControle = "Biológico",
                            TipoPraga = "Aracnídeo"
                        },
                        new
                        {
                            PragaId = "010",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Besouros",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "011",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Formigas",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "012",
                            ControleAdequado = "Rotação de culturas, solarização do solo",
                            NomeDaPraga = "Nematóides",
                            TipoControle = "Cultural",
                            TipoPraga = "Verme"
                        },
                        new
                        {
                            PragaId = "013",
                            ControleAdequado = "Rotação de culturas, remoção de plantas infestadas",
                            NomeDaPraga = "Cigarras",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "014",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Brocas",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "015",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Percevejos",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "016",
                            ControleAdequado = "Manejo adequado do solo, cobertura do solo",
                            NomeDaPraga = "Grilos",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "017",
                            ControleAdequado = "Rotação de culturas, manutenção de áreas limpas",
                            NomeDaPraga = "Gafanhotos",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "018",
                            ControleAdequado = "Plantio em sistemas que dificultem o acesso, uso de barreiras",
                            NomeDaPraga = "Minhocas Cortadeiras",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "019",
                            ControleAdequado = "Manutenção adequada da estrutura de madeira, remoção de madeiras deterioradas",
                            NomeDaPraga = "Bicho Carpinteiro",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "020",
                            ControleAdequado = "Rotação de culturas, uso de solo saudável",
                            NomeDaPraga = "Vermes",
                            TipoControle = "Cultural",
                            TipoPraga = "Verme"
                        },
                        new
                        {
                            PragaId = "021",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Psilídeos",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "022",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Cicadelídeos",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "023",
                            ControleAdequado = "Manutenção de áreas limpas, uso de armadilhas",
                            NomeDaPraga = "Bicho da Luz",
                            TipoControle = "Cultural",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "024",
                            ControleAdequado = "Uso de predadores naturais",
                            NomeDaPraga = "Aranhas",
                            TipoControle = "Biológico",
                            TipoPraga = "Aracnídeo"
                        },
                        new
                        {
                            PragaId = "025",
                            ControleAdequado = "Inseticida",
                            NomeDaPraga = "Gorgulhos",
                            TipoControle = "Químico",
                            TipoPraga = "Inseto"
                        },
                        new
                        {
                            PragaId = "026",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Oídio",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "027",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Ferrugem",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "028",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Míldio",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "029",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Antracnose",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "030",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Fusarinose",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "031",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Mofo",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "032",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Cytospora",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "033",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Mancha Foliar",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        },
                        new
                        {
                            PragaId = "034",
                            ControleAdequado = "Fungicida",
                            NomeDaPraga = "Podridão",
                            TipoControle = "Químico",
                            TipoPraga = "Fungo"
                        });
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.Property<string>("Lote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CategoriaProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ColheitaOrigemNumeroRegistro")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataValidade")
                        .HasColumnType("datetime2");

                    b.Property<string>("NomeProduto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Lote");

                    b.HasIndex("ColheitaOrigemNumeroRegistro");

                    b.ToTable("Produto");
                });

            modelBuilder.Entity("ProdutoVenda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ProdutoLote")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Quantidade")
                        .HasColumnType("bigint");

                    b.Property<int>("VendaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProdutoLote");

                    b.HasIndex("VendaId");

                    b.ToTable("ProdutoVenda");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnderecoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NomeCompleto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CPF");

                    b.HasIndex("EnderecoId");

                    b.ToTable("Usuario");

                    b.HasData(
                        new
                        {
                            CPF = "43625350807",
                            Ativo = true,
                            DataNascimento = new DateTime(2003, 6, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.luiza@gmail.com",
                            EnderecoId = "15997440120",
                            NomeCompleto = "Maria Luiza Guedes",
                            Senha = "malu123",
                            Telefone = "16 992663385",
                            Tipo = "Administrador"
                        },
                        new
                        {
                            CPF = "44416401884",
                            Ativo = true,
                            DataNascimento = new DateTime(2003, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rian.ortega@gmail.com",
                            EnderecoId = "159970101264",
                            NomeCompleto = "Rian Ortega",
                            Senha = "rian123",
                            Telefone = "16 992663385",
                            Tipo = "Agricultor"
                        },
                        new
                        {
                            CPF = "47584609831",
                            Ativo = true,
                            DataNascimento = new DateTime(1998, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amanda.ferreira@gmail.com",
                            EnderecoId = "14820768140",
                            NomeCompleto = "Amanda Ferreira",
                            Senha = "amanda123",
                            Telefone = "16 992663385",
                            Tipo = "Administrador"
                        },
                        new
                        {
                            CPF = "51005332851",
                            Ativo = true,
                            DataNascimento = new DateTime(2000, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dani.burk@gmail.com",
                            EnderecoId = "15997060350",
                            NomeCompleto = "Danielly Burkowski",
                            Senha = "dani123",
                            Telefone = "16 992663385",
                            Tipo = "Agricultor"
                        },
                        new
                        {
                            CPF = "53913441824",
                            Ativo = true,
                            DataNascimento = new DateTime(1998, 8, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.mazz@gmail.com",
                            EnderecoId = "15993081140",
                            NomeCompleto = "João Mazzoni",
                            Senha = "joao123",
                            Telefone = "+55 16 91234-5678",
                            Tipo = "Gerente"
                        },
                        new
                        {
                            CPF = "86135870033",
                            Ativo = true,
                            DataNascimento = new DateTime(1998, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "carine.souza@gmail.com",
                            EnderecoId = "148211642500",
                            NomeCompleto = "Carine Souza",
                            Senha = "carine123",
                            Telefone = "992663385",
                            Tipo = "Comercial"
                        });
                });

            modelBuilder.Entity("Fornecedor", b =>
                {
                    b.HasOne("Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Insumo", b =>
                {
                    b.HasOne("Fornecedor", "Fornecedor")
                        .WithMany()
                        .HasForeignKey("FornecedorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fornecedor");
                });

            modelBuilder.Entity("Models.AplicacaoInsumo", b =>
                {
                    b.HasOne("Insumo", "Insumo")
                        .WithMany()
                        .HasForeignKey("InsumoCodigoLote")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Plantacao", "Plantacao")
                        .WithMany()
                        .HasForeignKey("PlantacaoId");

                    b.Navigation("Insumo");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("Models.Cliente", b =>
                {
                    b.HasOne("Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Models.Colheita", b =>
                {
                    b.HasOne("Plantacao", "Plantacao")
                        .WithMany()
                        .HasForeignKey("PlantacaoId");

                    b.Navigation("Plantacao");
                });

            modelBuilder.Entity("Models.RegistroInfestacao", b =>
                {
                    b.HasOne("Plantacao", "Plantacao")
                        .WithMany()
                        .HasForeignKey("PlantacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Praga", "Praga")
                        .WithMany()
                        .HasForeignKey("PragaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plantacao");

                    b.Navigation("Praga");
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.HasOne("Models.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteCNPJ");

                    b.HasOne("Usuario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioCPF");

                    b.Navigation("Cliente");

                    b.Navigation("Funcionario");
                });

            modelBuilder.Entity("Produto", b =>
                {
                    b.HasOne("Models.Colheita", "ColheitaOrigem")
                        .WithMany()
                        .HasForeignKey("ColheitaOrigemNumeroRegistro")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColheitaOrigem");
                });

            modelBuilder.Entity("ProdutoVenda", b =>
                {
                    b.HasOne("Produto", "Produto")
                        .WithMany()
                        .HasForeignKey("ProdutoLote");

                    b.HasOne("Models.Venda", null)
                        .WithMany("Produtos")
                        .HasForeignKey("VendaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("Usuario", b =>
                {
                    b.HasOne("Models.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Models.Venda", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
